# Generated by Django 3.2.25 on 2024-03-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='role',
            new_name='usertype',
        ),
    ]
