# Generated by Django 3.2.25 on 2024-04-01 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_rename_role_signup_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='usertype',
            new_name='role',
        ),
    ]
